// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "GUI.h"

GUI::GUI() {
  { root = new Fl_Double_Window(945, 680, "Jack MIDI Logger");
    root->user_data((void*)(this));
    { sources = new Fl_Check_Browser(15, 125, 300, 550, "Sources");
      sources->labelfont(13);
      sources->textfont(13);
      sources->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Check_Browser* sources
    { messages = new Fl_Text_Display(330, 125, 600, 550, "Messages");
      messages->box(FL_DOWN_BOX);
      messages->color(FL_GRAY0);
      messages->textfont(13);
      messages->textcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Text_Display* messages
    { options = new Fl_Pack(330, 15, 600, 80);
      options->type(1);
      { notes = new Fl_Light_Button(570, 35, 80, 40, "Notes");
        notes->selection_color((Fl_Color)2);
      } // Fl_Light_Button* notes
      { cc = new Fl_Light_Button(660, 35, 80, 40, "CC");
        cc->selection_color((Fl_Color)2);
      } // Fl_Light_Button* cc
      { other = new Fl_Light_Button(750, 35, 80, 40, "Other");
        other->selection_color((Fl_Color)2);
      } // Fl_Light_Button* other
      { pretty = new Fl_Light_Button(840, 35, 80, 40, "Pretty");
        pretty->selection_color((Fl_Color)2);
      } // Fl_Light_Button* pretty
      options->end();
    } // Fl_Pack* options
    root->end();
  } // Fl_Double_Window* root
}
