// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef GUI_h
#define GUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Check_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Light_Button.H>

class GUI {
private:
  static void butPushPretty(Fl_Light_Button*, GUI*);
public:
  GUI();
  bool isPretty = false;
  Fl_Double_Window *root;
  Fl_Check_Browser *sources;
  Fl_Text_Display *messages;
  Fl_Text_Buffer *buffer_hexa;
  Fl_Text_Buffer *buffer_pretty;
  Fl_Pack *options;
  Fl_Light_Button *notes;
  Fl_Light_Button *cc;
  Fl_Light_Button *other;
  Fl_Light_Button *pretty;
};
#endif
